### ISSUE TITLE
The connector fails on JDK11+

### ISSUE THREAD

**Issue by jerrinot** [questdb/flink-questdb-connector#1]
```
jobmanager_1   | Caused by: java.lang.NoClassDefFoundError: sun/misc/FDBigInteger
jobmanager_1   | 	at io.questdb.std.Numbers.append(Numbers.java:2214) ~[flink-questdb-connector.jar:?]
jobmanager_1   | 	at io.questdb.std.Numbers.append(Numbers.java:255) ~[flink-questdb-connector.jar:?]
jobmanager_1   | 	at io.questdb.std.Numbers.append(Numbers.java:211) ~[flink-questdb-connector.jar:?]
jobmanager_1   | 	at io.questdb.std.str.CharSink.put(CharSink.java:109) ~[flink-questdb-connector.jar:?]
jobmanager_1   | 	at io.questdb.cutlass.line.AbstractLineSender.field(AbstractLineSender.java:145) ~[flink-questdb-connector.jar:?]
jobmanager_1   | 	at io.questdb.cutlass.line.AbstractLineSender.doubleColumn(AbstractLineSender.java:151) ~[flink-questdb-connector.jar:?]
jobmanager_1   | 	at io.questdb.cutlass.line.AbstractLineSender.doubleColumn(AbstractLineSender.java:46) ~[flink-questdb-connector.jar:?]
jobmanager_1   | 	at org.questdb.flink.QuestDBSinkWriter.write(QuestDBSinkWriter.java:68) ~[flink-questdb-connector.jar:?]
jobmanager_1   | 	at org.questdb.flink.QuestDBSinkWriter.write(QuestDBSinkWriter.java:36) ~[flink-questdb-connector.jar:?]
jobmanager_1   | 	at org.questdb.flink.QuestDBSinkWriter.write(QuestDBSinkWriter.java:22) ~[flink-questdb-connector.jar:?]
jobmanager_1   | 	at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.processElement(SinkWriterOperator.java:158) ~[flink-dist-1.15.2.jar:1.15.2]
jobmanager_1   | 	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) ~[flink-dist-1.15.2.jar:1.15.2]
jobmanager_1   | 	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57) ~[flink-dist-1.15.2.jar:1.15.2]
jobmanager_1   | 	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29) ~[flink-dist-1.15.2.jar:1.15.2]
jobmanager_1   | 	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56) ~[flink-dist-1.15.2.jar:1.15.2]
jobmanager_1   | 	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29) ~[flink-dist-1.15.2.jar:1.15.2]
jobmanager_1   | 	at StreamExecCalc$52.processElement(Unknown Source) ~[?:?]
jobmanager_1   | 	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) ~[flink-dist-1.15.2.jar:1.15.2]
jobmanager_1   | 	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57) ~[flink-dist-1.15.2.jar:1.15.2]
```
This is because the connector depends on questdb-jdk8 which has a hard dependency on classes unavailable post-jigsaw. 

Possible solutions:
- create 2 versions of the connector: jdk8 and jdk9+
- find a workaround inside questdb ILP client - so the jdk8 build works on jdk9+ too
- make JDK11+ a hard dependency
- do not shade questdb client inside the connector. so the user can/must choose what version of questdb to use

**Comment by jerrinot** [comment]
closed by 1539a60e7f4b22412f95676d2d0621ac6e8ed257
minimal requirements are now JDK11.
